"""create devices table

Revision ID: 0da06ae57d65
Revises: 001_baseline
Create Date: 2026-09-15 16:21:17.412510
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0da06ae57d65'
down_revision = '001_baseline'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), server_default=sa.text("'sensor'"), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_devices_role', 'devices', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_role', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###