"""add device family

Revision ID: fe8bf605675b
Revises: 0da06ae57d65
Create Date: 2026-09-23 10:28:56.327950
"""

from alembic import op
import sqlalchemy as sa


revision = 'fe8bf605675b'
down_revision = '0da06ae57d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_family', sa.String(length=32), server_default=sa.text("'simulation'"), nullable=False))
    op.create_index('ix_devices_family', 'devices', ['device_family'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_family', table_name='devices')
    op.drop_column('devices', 'device_family')
    # ### end Alembic commands ###